services:
  db:
    container_name: postgres
    image: postgres:17
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    volumes:
      - ./apps/backend/src:/app/apps/backend/src
      - ./packages:/app/packages
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on: 
      - db
    env_file: 
      - .env

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend/src:/app/apps/frontend/src
      - ./packages:/app/packages
    depends_on:
      - backend
    env_file:
      - .env

volumes:
  pgdata: