services:
  db:
    image: postgres:17
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: .env
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/lydurh/wde25_bachelor_project/backend:latest
    env_file: .env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    image: ghcr.io/lydurh/wde25_bachelor_project/frontend:latest
    expose:
      - '80'
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata: