services:
  db:
    container_name: postgres
    image: postgres:17
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "3000:3000"
    depends_on: 
      - db
    env_file: 
      - .env

  admin:
    container_name: admin
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./apps/admin/src:/app/apps/admin/src
      - ./packages:/app/packages
    depends_on:
      - backend
    env_file:
      - .env

volumes:
  pgdata: