FROM oven/bun:1-alpine
WORKDIR /app

COPY . .

RUN bun install --frozen-lockfile
RUN bun run --filter backend build

ENV NODE_ENV=production
ENV PORT=3000

EXPOSE 3000

CMD ["sh", "-c", "bun run --filter @repo/db db:migrate:prod && bun ./apps/backend/dist/index.js"]
